### ISSUE TITLE
Data set missing

### ISSUE THREAD

**Issue by prince09121996** [Sklyvan/Age-Gender-Prediction#1]
DefaultData/Train/images/
DefaultData/Validation/Labels/BoundingBoxes.txt
DATA/WIDER_VALIDATION/
/UTK' + '/Images/
these data set for both yolo and resnet training are missing

**Comment by Sklyvan** [comment]
Hello, thanks for opening an issue. This repository was made just for delivering a university project, so the datasets were not necessary to be uploaded. I do not have the data in the same format that is inside the GitHub repository, but I can send you the datasets.
- [WIDER Dataset](http://yjxiong.me/event_recog/WIDER/) (YOLO)
- [UTK Dataset](https://ufile.io/3xnnf2jm) (ResNet)
