### ISSUE TITLE
error

### ISSUE THREAD

**Issue by northstarintern02** [Sklyvan/Age-Gender-Prediction#2]
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 384 Expected: 640
 Please fix either the inputs or the model.

**Comment by NaturalStupidlty** [comment]
> [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
> index: 2 Got: 384 Expected: 640
> Please fix either the inputs or the model.

You need to resize your input PIL.Image for the detector model. You can do this with resize method from PIL
```

def returnAnalysis(imagePath):
    IMG = Image.open(imagePath)
    IMG = IMG.resize((640,640))
    IMG_ = ImageDraw.Draw(IMG)
    t0 = time.time()
    faces, bbs = extractFace(IMG, FaceDetector, 0.7)
    tt1 = time.time() - t0

    tt2 = 0
    for face, bb in zip(faces, bbs):
        IMG_.rectangle(bb, outline ="Red", width=2)
        tensorIMG = readImage(face)
        t0 = time.time()
        Age, Gender, C = extractInfo(FaceClassifier, tensorIMG)
        tt = time.time() - t0
        tt2 += tt
        textBox = f'{Age} {Gender}'
        Text = ImageDraw.Draw(IMG)
        Text.text((bb[0][0]+5, bb[0][1]+2), 
                    textBox, 
                    fill=(255, 0, 0))
    return IMG, tt1+tt2
```
